name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liKGf3fFzwzr154R"
GITHUB_OWNER = "andylu78"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.lu7788.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://dh.lu7788.dpdns.org"

